# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SparseGroupSLOPE <- function(X, y, lambda, alpha, BInit, intercept = TRUE, stepSize = 100, eta = 0.9, tol = 1e-5, maxIter = 1e5L, minStepSize = 1e-10, accelerated = FALSE, monotone = FALSE, saveData = FALSE, standardize = TRUE) {
    .Call(`_sparse_group_slope_SparseGroupSLOPE`, X, y, lambda, alpha, BInit, intercept, stepSize, eta, tol, maxIter, minStepSize, accelerated, monotone, saveData, standardize)
}

norm_sgs <- function(B, lambda, alpha) {
    .Call(`_sparse_group_slope_norm_sgs`, B, lambda, alpha)
}

